from enum import Enum


class EventType(str, Enum):
    STATE_SYNC = "STATE_SYNC"
    STATE_SYNC_REQUEST = "STATE_SYNC_REQUEST"
    DEVICE_EVENT = "DEVICE_EVENT"
    ASR_FRAGMENT = "ASR_FRAGMENT"
    USER_TEXT = "USER_TEXT"
    AI_RESPONSE = "AI_RESPONSE"
    RECORDING_STATE = "RECORDING_STATE"
    SIGNATURE_STATE = "SIGNATURE_STATE"
    PROTOCOL_ERROR = "PROTOCOL_ERROR"
